### ISSUE TITLE
workflow of the script

### ISSUE THREAD

**Issue by jihadaj** [tilmanmoser/bbb-video-download#10]
Firstly, many thanks for coming up with such a scirpt. we value your time you spend on this, which will serve the community better.

This is not an issue, but i didn't another way to get these answers.

Kindly let me know

1.  Am not able to track when this script will start the conversion to mp4. Does it take in account the load of the server and priority of CPUs ?

2. I have installed it on one of my production server, and would like to uninstall for time-being. What is the best way to uninstall the script ?

**Comment by tilmanmoser** [comment]
Hi there. I am not taking care about the current CPU load (as BBB is neither). But the script only uses one CPU Core/Thread at the time being per default.

To uninstall the script, you can simply rename /usr/local/bigbluebutton/core/scripts/post_publish/post_publish_bbb_video_download.rb to anything not ending in .rb. To completely remove the installation delete this script and the folder /opt/bbb-video-download.
