### ISSUE TITLE
Automation for all videos

### ISSUE THREAD

**Issue by Smartgendeveloper** [tilmanmoser/bbb-video-download#11]
I tried this repository in my BBB server and its working absolutely fine. Now I have a 100+ recordings in my server. So is there a way to do automation to build a .mp4 videos for all?

Thanking you.

**Comment by wolbernd** [comment]
For that task I wrote a shell script:
```
#!/bin/bash

BASEPATH=/var/bigbluebutton/published/presentation
LOGFILE=/var/log/videogenerator.log

for presentation in ${BASEPATH}/*; do
        ID=$(basename $presentation)
        VIDEOFILE="${BASEPATH}/${ID}/${ID}.mp4"
        echo "$(date) Processing ${ID}" >> $LOGFILE
        #Check if mp4 already exists
        if [ ! -e $VIDEOFILE ]; then 
                sudo -u bigbluebutton bash -c cd /srv/recstore/videogenerator; node /srv/recstore/videogenerator/index.js -i $presentation -o $VIDEOFILE >> $LOGFILE 2>> $LOGFILE
                if [ ! -e $VIDEOFILE ]; then
                        echo "Conversion of ${ID} failed" >> $LOGFILE
                fi
        else
                echo "$(date) ${ID} already has a video file - skipping" >> $LOGFILE
        fi
        echo "======================================================" >> $LOGFILE
done
```
Please check if the BASEPATH and LOGFILE variables work for your setup. Admittedly it's probably not the most elegant solution but it should get the job done.

**Comment by Smartgendeveloper** [comment]
Thanks for your prompt reply. 
Will try the above solution and let you know.
Is there any automation task like once the video gets published? it will automatically create a .mp4 video for us.

**Comment by wolbernd** [comment]
If you follow the installation instructions in https://github.com/tilmanmoser/bbb-video-download/blob/master/README.md a hook will be installed in BBB that runs the conversion process automatically after a presentation is published.

Please note that the mp4 filename might be different then the one create using my script. Since I don't use the hook I haven't checked for this.

**Comment by Smartgendeveloper** [comment]
I already followed the steps suggested by you in readme file. Let me check the file got created or not.


Thank a lot.
