### ISSUE TITLE
 [ffmetadata @ 0x55afda92f0c0] Chapter end time 3741565 before start 7517200

### ISSUE THREAD

**Issue by christmart** [tilmanmoser/bbb-video-download#14]
fails to build video.mp4 because of errors with ffmetadata:

I, [2020-10-08T02:01:02.046804 #1035]  INFO -- : [ffmetadata @ 0x55afda92f0c0] Chapter end time 3741565 before start 7517200
I, [2020-10-08T02:01:02.046836 #1035]  INFO -- : ./tmp/a407400b5a5e2c49f50fb3bf370556cc94186cc0-1602090261817/ffmetadata.txt: Cannot allocate memory
I, [2020-10-08T02:01:02.049864 #1035]  INFO -- : Error: Command failed: ffmpeg -y \

The last slide seams to have a wrong begintime:
from ffmetadata.txt:

[CHAPTER]
TIMEBASE=1/1000
START=3462900
END=7517200
title=Deskshare 3
[CHAPTER]
TIMEBASE=1/1000
START=7517200
END=3741565
title=Slide 1.3

Any idea why this failed?

**Comment by christmart** [comment]
I have a lot of recordings with this symptom .
Where can I look for the problem?
From which entries in which files are these START and END values filled?
Do you need any more logs or examples?

**Comment by christmart** [comment]
in modules/shapes.js:76 the END mark gets set to at most maxEnd which is set from the duration value from metadata.xml:

                Math.min(1 * image.$.out, maxEnd) 

The .in and .out values come from shapes.svg.

I think duration in metadata.xml is the duration of the meeting after cutting the parts which are not marked for recording.
And shapes.svg has the original timestamps.
So some end markers in shapes.svg can be later that duration.

**Comment by tilmanmoser** [comment]
Hi. Thanks for all your efforts and inputs. There'll be a new (rewritten) version available later today. It won't have chapter marks for now, but improved video quality with slides/deskshares/zooms/cursors/webcams/captions.
