### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by amirhnader** [tilmanmoser/bbb-video-download#15]
Hi,

Could you please help me how to remove(uninstall) bbb-video-download ?

Thanks,
Amiroo

**Comment by amousavii** [comment]
up to version 1.0.x:

rm /usr/local/bigbluebutton/core/scripts/post_publish/post_publish_bbb_video_download.rb
rm -r /opt/bbb-video-download
from version 1.1.x on:

rm /usr/local/bigbluebutton/core/scripts/post_publish/a0_post_publish_bbb_video_download.rb
rm -r /opt/bbb-video-download

**Comment by tilmanmoser** [comment]
As stated before, to uninstall just remove the post publish hook and the installation directory. (Updated README.md as well)
