### ISSUE TITLE
Error: spawnSync /bin/sh E2BIG 

### ISSUE THREAD

**Issue by christmart** [tilmanmoser/bbb-video-download#16]
fails to execute ffmpeg because of too long command line.

We have a lot of recorded lecture meetings with a bunch of slides and a huge amount of cursor movements and drawings.
I have seen e.g. about 20000 drawboxes and about 3000 pencil pngs. This results in a command line of more than MAX_ARGS=2097152 bytes which are allowed an execve system call.

Is there a possibility to split the ffmpeg calls into separate calls where the command line is below the MAX_ARGS limit?

I can provide logs.

**Comment by wolbernd** [comment]
@christmart This problem is already being worked on. See #6

**Comment by tilmanmoser** [comment]
And this issue should be fixed. There's still a bug regarding desksharing, which I'll fix today or latest tomorrow.
