### ISSUE TITLE
post_publish_bbb_video_download.rb should got to post_process

### ISSUE THREAD

**Issue by christmart** [tilmanmoser/bbb-video-download#17]
I think *bbb_video_download.rb should be called in post_process and not in post_publish.

In post_publish are normally scripts that depend on the finished recording processing like for example the scalelite_recording_importer.

At the moment the scalelite importer is called after the video_download script because of the alphabetical ordering (s after r)
The publish script sets at its end of its processing the marker status/published/xxxx-presentation.done to indicate that its done.
But the video_download script might still run for a long time.

**Comment by christmart** [comment]
I had a look into publish/presentation.rb
It might be that in this script is more processing that must run before bbb_video_download.rb .

The we have to make sure that it is run before scripts like scalelite...

**Comment by tilmanmoser** [comment]
Since the scripts works with the published files it will remain in post_publish. Though you can adjust the name, so it's called in the right order.
