### ISSUE TITLE
Conversion Failed!

### ISSUE THREAD

**Issue by advaitn** [tilmanmoser/bbb-video-download#2]
Hi,

Thanks for sharing your amazing work, I tried this on my BBB installation, but sadly the logs don't say according to the plan.

Here is the output of error:

> Press [q] to stop, [?] for help
> [libx264 @ 0x55e8fbf1a240] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
> [libx264 @ 0x55e8fbf1a240] profile High, level 4.0
> [libx264 @ 0x55e8fbf1a240] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
> [mp4 @ 0x55e8fbf14f40] track 1: codec frame size is not set
> [mp4 @ 0x55e8fbf14f40] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
> Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
> Error initializing output stream 0:0 -- 
> **Conversion failed!**
> 
>     at Processor.createVideo (/opt/bbb-video-download/modules/processor.js:60:19)
>     at async process (/opt/bbb-video-download/index.js:26:9)
> 
> I, [2020-08-31T22:39:25.244493 #29106]  INFO -- : Create downloadable video for [c7478e38fb4df17285e6684fb7deb158b88601e7-1598899280653] end
> I, [2020-08-31T22:39:25.731900 #29440]  INFO -- : Task: Getting meeting metadata
> I, [2020-08-31T22:39:25.744377 #29440]  INFO -- : Recording Ready Notify for [c7478e38fb4df17285e6684fb7deb158b88601e7-1598899280653] starts
> I, [2020-08-31T22:39:25.744413 #29440]  INFO -- : Recording Ready notify ends

Could you please look into this issue?

**Comment by tilmanmoser** [comment]
Hi @advaitn - thanks for reporting that issue. It helps me to improve my code. 

According to this [thread at stackoverflow](https://stackoverflow.com/questions/54192916/error-opus-in-mp4-support-is-experimental-add-strict-2-if-you-want-to-use), this issue is related to an outdated ffmpeg version. 

In version 1.0.2 I reordered the global and output options, i.e. "-y" is now placed before inputs and added "-strict -2" before the outputfile. This doesn't break my code on newer ffmpeg versions as tested on my machine, but I don't have a machine with your specs to test it with an older version of ffmpeg. Can you verify, if this solves your problem?

**Comment by advaitn** [comment]
Excellent, that solved the issue.

I still have another issue the videos do get exported in the required format but they don't show on the playback page in a similar context.

https://live.grtf.in/playback/presentation/2.0/playback.html?meetingId=c7478e38fb4df17285e6684fb7deb158b88601e7-1598899280653

You can check here.

Thanks!

**Comment by tilmanmoser** [comment]
Your video can be accessed via https://live.grtf.in/presentation/c7478e38fb4df17285e6684fb7deb158b88601e7-1598899280653/video.mp4

I don‘t intend to modify the bbb player.

**Comment by advaitn** [comment]
Oh, it's alright then. I actually referred to your reference :

> You can compare it here:
> BBB Playback: https://meet.impavit.com/playback/presentation/2.0/playback.html?meetingId=9a9b6536a10b10017f7e849d30a026809852d01f-1598793065462
> Video: https://meet.impavit.com/presentation/9a9b6536a10b10017f7e849d30a026809852d01f-1598793065462/video.mp4

Any idea how I can achieve that? 🥇

**Comment by tilmanmoser** [comment]
The video is stored in the presentation folder as video.mp4 - so you can always access it at https://your-server/presentation/<presentationid>/video.mp4 

I distribute the downloads via our website. You can of course also change the player html code to display a download button.

**Comment by advaitn** [comment]
> The video is stored in the presentation folder as video.mp4 - so you can always access it at https://your-server/presentation/%presentationid%/video.mp4
> 
> I distribute the downloads via our website. You can of course also change the player html code to display a download button.

Ok great, thanks for the quick reply!
