### ISSUE TITLE
Slides are blank for some recordings

### ISSUE THREAD

**Issue by miriyusifli** [tilmanmoser/bbb-video-download#24]
I was able to convert multiple recordings into m4 files yesterday. Today I pulled the last commits and tested again. It seems that, code is broken after d0036f5a2d780a031d3f7b05b55d84b3165df9f5 105258d1003c29023e2a7e2b8dfe1620f83d3a52 commits. 
I have tested both versions of the script again and the first version (before mentioned commits) works as expected while the second version (last version) doesn't work.

The problem with the second version is that slides are shown as blank (white) for some mp4 recordings.

**Comment by tilmanmoser** [comment]
Please retest with v1.1.3

**Comment by miriyusifli** [comment]
Solved :+1:  Thanks
