### ISSUE TITLE
Able to download part of video during composing

### ISSUE THREAD

**Issue by archidn** [tilmanmoser/bbb-video-download#28]
I suggest write a file to temp/video.mp4
or maybe ./partialvideo.mp4
and when it ts ready, just move/rename it to video.mp4
because otherwise users will download incorrect files and cry.

**Comment by tilmanmoser** [comment]
Thanks for sharing this issue. It's fixed in v1.2.1. The video is rendered in tmp dir and only copied when everything is rendered.
