### ISSUE TITLE
Error in conversion

### ISSUE THREAD

**Issue by akhtarkamal1-ed** [tilmanmoser/bbb-video-download#3]
Hello

I am getting the following error when converting when using the manual video creation option:

./node12/bin/node index.js -I /var/bigbluebutton/published/presentation/<meetingid> -o output-file-name.mp4

Error: Error: Error: Command failed: ffmpeg -hide_banner -loglevel panic -loop 1 -framerate 25 -t 7220.372 -i ./tmp/e7300c0a5cef4ba644d627e3fd7882c140aa0496-1598706779500/canvas.png -c:v libx264 -vf "format=yuv420p" ./tmp/e7300c0a5cef4ba644d627e3fd7882c140aa0496-1598706779500/canvas.mp4
    at Processor.createAssets (/opt/bbb-video-download/modules/processor.js:50:19)
Error: Error: Error: Command failed: ffmpeg -hide_banner -loglevel panic -loop 1 -framerate 25 -t 7220.372 -i ./tmp/e7300c0a5cef4ba644d627e3fd7882c140aa0496-1598706779500/canvas.png -c:v libx264 -vf "format=yuv420p" ./tmp/e7300c0a5cef4ba644d627e3fd7882c140aa0496-1598706779500/canvas.mp4
    at Processor.createAssets (/opt/bbb-video-download/modules/processor.js:50:19)

e7300c0a5cef4ba644d627e3fd7882c140aa0496-1598706779500 is the meeting id for reference.

Any suggestions please?

**Comment by akhtarkamal1-ed** [comment]
Update: Ran another meeting and this time chose to have the post_publish script do the conversion:

Here is the error in /var/log/bigbluebutton/post_publish.log

Error: Error: EACCES: permission denied, mkdir '/opt/bbb-video-download/tmp/bd9b1807d7177f84ef920ba47fa1df887b299f6f-1599077723543'
    at Processor.createAssets (/opt/bbb-video-download/modules/processor.js:50:19)

Ran the install.sh script as root:

sudo ./install.sh so not sure why the permissions problem.

**Comment by tilmanmoser** [comment]
It seems that the user running the script has no write permission on the install folder. I.e. either the folder does bot belong to bigbluebutton or the script is not executed as bigbluebutton. Check if there is already a tmp folder in the installation folder and the owner is set correctly. Alternatively create a tmp folder in the installation dir and set the rights as `chmod a+rw ./tmp`, so that all users can read/write in it.

**Comment by akhtarkamal1-ed** [comment]
The directory tmp under /opt/bbb-video-download is created successfully on post-publish. 

To test this I deleted the directory tmp and ran a meeting. The tmp directory is created fine.

Here is the error it now gives under /var/log/bigbluebutton/post_publish.log

Error: TypeError: Cannot read property 'includes' of undefined
    at Processor.createAssets (/opt/bbb-video-download/modules/processor.js:50:19)

By the way the installation was done completely using root.

**Comment by tilmanmoser** [comment]
Thanks for detecting this :-) There are only two places in the code, where I use string operation "includes" - I added additional checks, that the variable is not undefined there. Provided version 1.0.3. Can you please verify, if this solves your problem? Thanks!

**Comment by akhtarkamal1-ed** [comment]
Thank you for writing back.

But now I get this under /var/log/bigbluebutton/post_publish.log

Error: Error: Error: Command failed: ffmpeg -hide_banner -loglevel panic -loop 1 -framerate 25 -t 53.204 -i ./tmp/057643c5f83384fc388bc14fa7f55d0e0f38b0b8-1599124120599/canvas.png -c:v libx264 -vf "format=yuv420p" ./tmp/057643c5f83384fc388bc14fa7f55d0e0f38b0b8-1599124120599/canvas.mp4
    at Processor.createAssets (/opt/bbb-video-download/modules/processor.js:50:19)

Also if I run below:

./node12/bin/node index.js -i /var/bigbluebutton/published/presentation/057643c5f83384fc388bc14fa7f55d0e0f38b0b8-1599124120599 -o 057643c5f83384fc388bc14fa7f55d0e0f38b0b8-1599124120599.mp4

I get:

Error: Error: Error: Command failed: ffmpeg -hide_banner -loglevel panic -loop 1 -framerate 25 -t 53.204 -i ./tmp/057643c5f83384fc388bc14fa7f55d0e0f38b0b8-1599124120599/canvas.png -c:v libx264 -vf "format=yuv420p" ./tmp/057643c5f83384fc388bc14fa7f55d0e0f38b0b8-1599124120599/canvas.mp4
    at Processor.createAssets (/opt/bbb-video-download/modules/processor.js:50:19)

Have reinstalled the version 1.0.3 you sent.

Also please note that tmp folder is being created by Bigbluebutton without problem and I can also see the folder of meetingid created under it. 

Any suggestions please.

**Comment by tilmanmoser** [comment]
Since your presentation is only 53seconds long I assume it‘s just a test? Can you provide me the folder /var/bigbluebutton/published/presentation/057643c5f83384fc388bc14fa7f55d0e0f38b0b8 as download so that I can test it locally? Thanks.

**Comment by akhtarkamal1-ed** [comment]
Apologies for the delayed response.

Here you go. Attached is the folder for the specific meeting ID.

[folder.zip](https://github.com/tilmanmoser/bbb-video-download/files/5170335/folder.zip)

**Comment by tilmanmoser** [comment]
Fixed in v1.0.5 - the problem was, that your widest slide has an odd height (899). MP4 only accepts heights dividable by 2. The scripts now ceils now to the next even number in height; i.e. your slide is rendered with 900px height.

**Comment by akhtarkamal1-ed** [comment]
Worked perfectly on the 53 sec presentation.

On a larger presentation about 2 hours in length, it ran for about 25 min and then gave this error.

error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 25460,
  stdout: null,
  stderr: null

No video.mp4 was created.

If this related to a FFMPEG Buffer overrun or your code?

Its a fairly powerful machine with 24 vCPUs and 40GB RAM. CPU utilisation was at 25% so doesn't seems it should have run out of memory or processing capacity.

Any suggestions?

**Comment by tilmanmoser** [comment]
The error says that the child process than ran ffmpeg returned nothing or got a sigterm. Have a look in /var/log/bigbluebutton/post_publish.log - the ffmpeg cmd is logged. Try to rerun it in shell, so you see ffmpeg output. Let me see the output.

**Comment by akhtarkamal1-ed** [comment]
Thank you.

This meeting did not go through the post_publish script as it was already there on the serve.

I had used the manual command ./node12/bin/node index.js to try and create a video from it.

Hence the post_publish.log has no output.

Does ffmpeg log anywhere?

**Comment by tilmanmoser** [comment]
Well then the ffmpeg cmd should have been outputted to the console before it started processing.
