### ISSUE TITLE
Screen sharing is cropped

### ISSUE THREAD

**Issue by miriyusifli** [tilmanmoser/bbb-video-download#34]
Screen sharing scaling is not correct after b3bc157cfb10464136ca89e9a72b5e9afca1f6b0 commit.
I have tested both versions of the script and the first version (before b3bc157cfb10464136ca89e9a72b5e9afca1f6b0 commit) shows the full size of the screen sharing as expected while the second version (last version) crops the screen sharing.

The first version
![first version](https://user-images.githubusercontent.com/18422143/98100539-4c0ddc00-1e91-11eb-9df7-b3c82edc3e5a.png)

The second version
![second version](https://user-images.githubusercontent.com/18422143/98100559-529c5380-1e91-11eb-9f5b-856fa5747db9.png)

**Comment by archidn** [comment]
yet another [crop issue](https://github.com/tilmanmoser/bbb-video-download/issues/29)  :)

**Comment by tilmanmoser** [comment]
Fixed in v1.2.1
