### ISSUE TITLE
Video folder

### ISSUE THREAD

**Issue by Ronald-For-Ever** [tilmanmoser/bbb-video-download#35]
Hello, 
first, Thank you for this script !

I have installed your script on my BBB server automatically, however I don't know in which directory the video to download is located. Can you tell me the path ? 

Thank you in advance.

**Comment by realsarm** [comment]
```
/var/bigbluebutton/published/presentation/
```

**Comment by archidn** [comment]
/var/bigbluebutton/published/presentation/manydigits/video.mp4
