### ISSUE TITLE
Integration in greenlight

### ISSUE THREAD

**Issue by christmart** [tilmanmoser/bbb-video-download#38]
Hi Tilman, thanks for your work on bbb-video-download.

We are using it in our setup and have adapted the greenlight-integration from https://gitlab.rlp.net/rzht-public/3b-download to work with bbb-video-download. The author of 3b-download gave the permission to publish this solution.

The idea ist to inject some js-code with the help of nginx into greenlight to get an aditional button on the greenlight recordings page below the presentation button.

If this is ok for you, I can make a pull request . It consists of some files:

/opt/bbb-download/htdocs/injector.js
/opt/bbb-download/htdocs/index.php
/opt/bbb-download/etc/config.inc.php

and some lines of nginx config.

**Comment by ichdasich** [comment]
So, what I do, what is probably easier, is check on the scalelite loadbalancer if there is a video present, and if so, add another presentation format to the DB. This could be done analogously for non-scalelite setups; Please see the code below:

```
#!/usr/bin/python3
import os
import re
import sys

import psycopg2
conn = psycopg2.connect("dbname=scalelite user=scalelite password=DBPASSWD host=DBHOST")


def create_download_link(meetingid):
#	print("Getting "+meetingid)
	cur = conn.cursor()
	cur.execute("SELECT id FROM recordings WHERE record_id = %s;", (meetingid,))
	recordingid = cur.fetchall()
	if not recordingid:
#		print('No record found')
		sys.exit(0)
	else:
		cur.execute("SELECT * FROM playback_formats WHERE format = 'download' AND recording_id = %s;", (recordingid[0][0],))
		download = cur.fetchall()
		if not download:
			cur.execute("SELECT length FROM playback_formats WHERE format = 'presentation' AND recording_id = %s;", (recordingid[0][0],))
			length = cur.fetchall()
			cur.execute("INSERT INTO playback_formats (recording_id, format, url, length) VALUES (%s, 'download', %s, %s);", (recordingid[0][0],"/presentation/"+meetingid+"/video.mp4",length[0][0]))
			conn.commit()
#		else:
#			print("record exists; Exiting")

def check_video_mp4(meetingid):
	f = "/srv/nfsroot/recordings/var/bigbluebutton/published/presentation/"+meetingid+"/video.mp4"
	if os.path.isfile(f):
		return True
	else:
		return False

def get_meeting_ids():
	cur = conn.cursor()
	cur.execute("SELECT record_id FROM recordings")
	meetings = cur.fetchall()
	
	for m in meetings:
		if m:
			if check_video_mp4(m[0]):
				create_download_link(m[0])


get_meeting_ids()
```

**Comment by tilmanmoser** [comment]
@christmart - can you provide source? I'll test both solutions and could add them as optional/manual install for those who are interested.

**Comment by archidn** [comment]
I am interested too, because I implanted not a button, but a simple link into dropdown menu of some .erb file... and this link is present even no file ready.

**Comment by christmart** [comment]
> @christmart - can you provide source? I'll test both solutions and could add them as optional/manual install for those who are interested.

Have a look at https://github.com/christmart/bbb-video-download/tree/master/greenlight .

**Comment by lonesomewalker** [comment]
> Have a look at https://github.com/christmart/bbb-video-download/tree/master/greenlight .

Erm, additionally install php-fpm on a BBB server?
I don't think that this is such a good idea...

**Comment by ichdasich** [comment]
Well, just use the script I posted above to add the download video link instead then. ;-)

**Comment by lonesomewalker** [comment]
> Well, just use the script I posted above to add the download video link instead then. ;-)

Already did that, works :-) Thank you for this "non-invasive" solution.
But i just wanted to comment @christmart that i know this solution, but since PHP is not known for security... i would not recommend this :P

**Comment by christmart** [comment]
I also think that the solution with registering the videos in the database is the better way.
But the script only solves the issue for greenlight, because greenlight does not use a recording-ready-url as a callback but askes everytime via API for the list of recordings.
Other integrations like moodle or mattermost set the recording-ready-url.
This url gets called from BBB after the normal video processing.
So we need to add this to the python script.

**Comment by tilmanmoser** [comment]
Wouldn‘t it be a better solution to get an email when the recording is ready? One could hook a script in bbb chain.

**Comment by christmart** [comment]
Would love to do that or even move the recordings do a video plattform like opencast or panopto automaticaly.
But you don't get the email address or the userid of the owner of the room in the BBB-backend. You only get what the frontend like greenlight, moodle, mattermost etc. passes on via the BBB-api as metadata.

**Comment by tilmanmoser** [comment]
Hi. If you want to code that, it‘s possible:
When the bbb room is created the api allows to pass metadata. Greenlight passes the room name for example. You could fork greenlight to pass whatever info you need. This metadata is stored in metadata.xml in the presentation folder. So you could parse that with a post hook script and do the desired actions.
