### ISSUE TITLE
Last minutes containing slides after a screen sharing are missing from the recording

### ISSUE THREAD

**Issue by Steffen75** [tilmanmoser/bbb-video-download#39]
I have a recording of a session that switches from screen sharing to slides for the last minutes. When I rewatch the session on the web this switch is working fine.
But when recording it using bbb-video-download the left half of the screen stays white after that switch.
The strange thing is when I watch the slides.mp4 in the /tmp folder the last slides are in it.

What goes wrong here when combining everything for the video?

**Comment by tilmanmoser** [comment]
Which version are you using? Do you have log outputs?

**Comment by Steffen75** [comment]
My version is 1.2.0.

The strange thing is that a second try afterwards went fine.

Where can I find the logs?

**Comment by tilmanmoser** [comment]
v1.2.0 had memory issues, which are resolved in v1.2.1. The latest version has proved to be pretty stable with all kinds of records. Please update...

**Comment by Steffen75** [comment]
Done that. Let's see how the next conversion of a recording turns out.

BTW have you updated the version number in the code? My first install was 1.2.0, git just pulled some stuff but checking the version from the shell still says 1.2.0.

**Comment by tilmanmoser** [comment]
Thanks for pointing that out. The version nr in package.json was updated.

**Comment by tilmanmoser** [comment]
Did v1.2.1 solve your problem?

**Comment by Steffen75** [comment]
I just made another try with the real version 1.2.1. This has worked out fine.

I guess we can close this.
