### ISSUE TITLE
Selecting resolution

### ISSUE THREAD

**Issue by dfaure-kdab** [tilmanmoser/bbb-video-download#4]
Can the user of this plugin choose the resolution of the resulting mp4?
Ideally one could even set the size of the slides and the size of the webcams...

**Comment by tilmanmoser** [comment]
In v1.0.4 now you can call the script with `--slides-width int` and `--webcams-width int`. Defaults are 1280 and 640, resulting in either 1280 (only slides/deskshare), 1920 (slides & webcams) or 640 (webcams only). However, you can set any odd resultion like slides 100, webcams 1000, if you like. Height of the overall video is derived from whatever part is higher.

Have fun.

**Comment by tilmanmoser** [comment]
If that suits your needs please close the issue :-) You're welcome.

**Comment by dfaure-kdab** [comment]
Thanks!
