### ISSUE TITLE
screen share size is not the correct dimension with webcam 

### ISSUE THREAD

**Issue by aaswaisi** [tilmanmoser/bbb-video-download#40]
When the recording is contained on the webcam with screen sharing, parts of the screen sharing video are truncated so that the screen share size is not the correct dimension.

**Comment by tilmanmoser** [comment]
Hi. Thanks for using bbb-video-download. Can you provide more specific description of your problem? Like screenshots of actual output vs expected output (from bbb player)? Thanks.

**Comment by aaswaisi** [comment]
![vv](https://user-images.githubusercontent.com/22277189/98991186-2d17e580-2534-11eb-9168-31990b655669.JPG)
.
.
The screen-sharing video is not the right dimensions, there is a cut-out part of the width dimensions.

**Comment by tilmanmoser** [comment]
Which version are you using? Does the video contain only screenshare and webcam?

**Comment by aaswaisi** [comment]
i used version 1.1.3 ,the video contain only screenshare and webcam

**Comment by tilmanmoser** [comment]
Well. Please update to latest v1.2.1

**Comment by aaswaisi** [comment]
Thank you so much, the problem has been solved. ♥
