### ISSUE TITLE
License for MPEG

### ISSUE THREAD

**Issue by cod3r0k** [tilmanmoser/bbb-video-download#42]
Hi, what is MPEG license which you mentioned in the read me? 

`
Info for server administrators
MPEG4 is not a free format. You may need to obtain a license to use this script on your server.
`

**Comment by tilmanmoser** [comment]
Let me google that for you... https://en.wikipedia.org/wiki/MPEG-4#Licensing

**Comment by cod3r0k** [comment]
What happened if we don't buy a license?

**Comment by tilmanmoser** [comment]
I‘m not the patent holder. Can‘t answer that...

**Comment by christmart** [comment]
Would it be an option to alternatively or additionaly have webm like BBB itself does?

**Comment by alexanderjackson** [comment]
> Would it be an option to alternatively or additionaly have webm like BBB itself does?

You can try our fork at https://github.com/SyncwerkGmbH/bbb-video-download. Hope it helps..

**Comment by tilmanmoser** [comment]
Hi there. webm should work with the latest version as well. However, it's not as well tested as mp4 from my side. The thought behind is simple: Since iOS devices don't support webm, mp4 is my preferred format, which is more widely supported.

**Comment by alexanderjackson** [comment]
Yes, I understand the thought behind using the MP4 format. Nevertheless, I think it's safer to promote the WebM (libvpx-vp9, libopus) codecs by default and only provide MP4 optionally with an obvious disclaimer that users are urged to ensure not to violate any patents and/or potential licensing issues when using MP4 with libx264 and AAC codecs - especially when used in a commercial environment. I think this is also the reason why Blindside Networks uses libvpx-vp(8|9) and libopus by default.

@tilmanmoser Is there a configuration switch that I missed in your project?

**Comment by tilmanmoser** [comment]
The script itself can be called with mp4 or webm target video. The provided hook must be adapted to the desired format as you did in your fork. I'll update the documentation to point this out.

**Comment by alexanderjackson** [comment]
Ahh, that wasn't clear before. Thanks!
