### ISSUE TITLE
Error when running the rebuild command old version of bbb

### ISSUE THREAD

**Issue by MOPO3KO** [tilmanmoser/bbb-video-download#43]
Hey.
I am using an old version of BBB, the update is complicated by a number of reasons that require a fight, but the main one is the lack of the Internet on the server (it is forbidden to enable it).
**The current script, when running, gives an error:**

bbb@ubuntu:/opt/bbb-video-download$ sudo -u bigbluebutton docker-compose run --rm --user 997:997 app node index.js -i /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595 -o /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4
[Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595', output='/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4'),
  format: 'mp4',
  docker: true
}
mv: can't create '/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4': Permission denied
[Error] Failed rendering downloable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595', output='/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4'),
  format: 'mp4',
  docker: true,
  workdir: './tmp/dataBnGdDN'
} Error: Command failed: mv ./tmp/dataBnGdDN/video.mp4 /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4
mv: can't create '/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4': Permission denied

    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at moveFile (/home/bigbluebutton/modules/processor.js:101:22)
    at module.exports.createVideo (/home/bigbluebutton/modules/processor.js:34:9)
    at async run (/home/bigbluebutton/index.js:10:9) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6d 76 3a 20 63 61 6e 27 74 20 63 72 65 61 74 65 20 27 2f 76 61 72 2f 62 69 67 62 6c 75 65 62 75 74 74 6f 6e 2f 70 75 62 6c 69 73 68 65 64 2f 70 72 65 ... 95 more bytes>
  ],
  pid: 259,
  stdout: <Buffer >,
  stderr: <Buffer 6d 76 3a 20 63 61 6e 27 74 20 63 72 65 61 74 65 20 27 2f 76 61 72 2f 62 69 67 62 6c 75 65 62 75 74 74 6f 6e 2f 70 75 62 6c 69 73 68 65 64 2f 70 72 65 ... 95 more bytes>
}

**at command output:**
`cat /etc/passwd | grep bigbluebutton`

**получаю:**
`bigbluebutton:x:997:997:bbb-apps-akka user-daemon:/home/bigbluebutton:/bin/false`

**ls -l** : `drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Nov 18 17:25 tmp`

of course I am aiming to update the version, but it is not up to me ...

please, tell me how to get out of the situation at the moment?

**Comment by tilmanmoser** [comment]
To whom does the folder /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/ belong to? Apparently the user executing the script has no right to write into that folder.

**Comment by MOPO3KO** [comment]
> To whom does the folder /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/ belong to? Apparently the user executing the script has no right to write into that folder.

and there is
`drwxr-xr-x 4 tomcat7 tomcat7`
this was the default in the old version

**Comment by tilmanmoser** [comment]
Basically you need to run the script as a user that has read access to the input folder (-i) and write access to the output folder (-o). So either you render the video to another output location (which you need to mount as a volume in docker-compose.yml) or you try to run the script with the tomcat7 user (don't forget to add tomcat7 to the docker group then).

You can ofcourse also set write permission for everyone on the output folder, which I DO NOT recommend.

**Comment by MOPO3KO** [comment]
please tell me how  (which you need to mount as a volume in docker-compose.yml)

**Comment by MOPO3KO** [comment]
I added
`sudo usermod -aG bigbluebutton,docker tomcat7`
but unfortunately I cannot get the automatic start of the video conversion by running
`sudo bbb-record --rebuild 5941b4e7060e134bb7389947897204258fdf5a11-1603880721595`
please tell me where can I see the problems of automatic conversion start?

**Comment by MOPO3KO** [comment]
I am completely confused how to understand from which record ruby is started
error in the log:

I, [2020-11-18T19:39:46.696577 #18923]  INFO -- : Executing: ruby publish/presentation.rb -m 5941b4e7060e134bb7389947897204258fdf5a11-1603880721595-presentation
I, [2020-11-18T19:39:47.274308 #18923]  INFO -- : 5941b4e7060e134bb7389947897204258fdf5a11-1603880721595-presentation
I, [2020-11-18T19:39:47.274477 #18923]  INFO -- : 5941b4e7060e134bb7389947897204258fdf5a11-1603880721595
I, [2020-11-18T19:39:47.274521 #18923]  INFO -- : presentation
I, [2020-11-18T19:39:47.274555 #18923]  INFO -- : presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1603880721597/slide-1.png : 0.0 -> 75.2
I, [2020-11-18T19:39:47.274586 #18923]  INFO -- : presentation/ebb1b787e6352d68943b31a0ac9c1c15aa6062c2-1603882111755/slide-1.png : 75.2 -> 84.4
I, [2020-11-18T19:39:47.274636 #18923]  INFO -- : presentation/ebb1b787e6352d68943b31a0ac9c1c15aa6062c2-1603882111755/slide-2.png : 84.4 -> 87.2
I, [2020-11-18T19:39:47.274667 #18923]  INFO -- : presentation/ebb1b787e6352d68943b31a0ac9c1c15aa6062c2-1603882111755/slide-3.png : 87.2 -> 89.3
I, [2020-11-18T19:39:47.274697 #18923]  INFO -- : presentation/ebb1b787e6352d68943b31a0ac9c1c15aa6062c2-1603882111755/slide-4.png : 89.3 -> 92.8
I, [2020-11-18T19:39:47.274727 #18923]  INFO -- : presentation/ebb1b787e6352d68943b31a0ac9c1c15aa6062c2-1603882111755/slide-5.png : 92.8 -> 746.4
I, [2020-11-18T19:39:47.281213 #18923]  INFO -- : Exit status: 0
I, [2020-11-18T19:39:47.281926 #18923]  INFO -- : Publish format presentation succeeded for 5941b4e7060e134bb7389947897204258fdf5a11-1603880721595
I, [2020-11-18T19:39:47.282507 #18923]  INFO -- : Running post publish script a0_post_publish_bbb_video_download
I, [2020-11-18T19:39:47.282903 #18923]  INFO -- : Executing: ruby post_publish/a0_post_publish_bbb_video_download.rb -m 5941b4e7060e134bb7389947897204258fdf5a11-1603880721595
I, [2020-11-18T19:39:49.180715 #18923]  INFO -- : [Error] Failed rendering downloable video for BBB presentation  {
I, [2020-11-18T19:39:49.180932 #18923]  INFO -- :   args: Namespace(input='/var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595', output='/var/bigbluebutton/published/presentation/5941b4e7060$
I, [2020-11-18T19:39:49.181007 #18923]  INFO -- :   format: 'mp4',
I, [2020-11-18T19:39:49.181068 #18923]  INFO -- :   docker: true
I, [2020-11-18T19:39:49.181128 #18923]  INFO -- : } Error: EACCES: permission denied, mkdtemp './tmp/dataXXXXXX'
I, [2020-11-18T19:39:49.181186 #18923]  INFO -- :     at Object.mkdtempSync (fs.js:1869:3)
I, [2020-11-18T19:39:49.181245 #18923]  INFO -- :     at module.exports.createVideo (/home/bigbluebutton/modules/processor.js:13:25)
I, [2020-11-18T19:39:49.181304 #18923]  INFO -- :     at run (/home/bigbluebutton/index.js:10:15)
I, [2020-11-18T19:39:49.181362 #18923]  INFO -- :     at Object.<anonymous> (/home/bigbluebutton/index.js:20:1)
I, [2020-11-18T19:39:49.181420 #18923]  INFO -- :     at Module._compile (internal/modules/cjs/loader.js:1015:30)
I, [2020-11-18T19:39:49.181534 #18923]  INFO -- :     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
I, [2020-11-18T19:39:49.181618 #18923]  INFO -- :     at Module.load (internal/modules/cjs/loader.js:879:32)
I, [2020-11-18T19:39:49.181680 #18923]  INFO -- :     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
I, [2020-11-18T19:39:49.181738 #18923]  INFO -- :     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
I, [2020-11-18T19:39:49.181798 #18923]  INFO -- :     at internal/main/run_main_module.js:17:47 {
I, [2020-11-18T19:39:49.181854 #18923]  INFO -- :   errno: -13,
I, [2020-11-18T19:39:49.181911 #18923]  INFO -- :   syscall: 'mkdtemp',
I, [2020-11-18T19:39:49.181968 #18923]  INFO -- :   code: 'EACCES',
I, [2020-11-18T19:39:49.182026 #18923]  INFO -- :   path: './tmp/dataXXXXXX'

**if you start the conversion in manual mode, then everything is fine, and if a new one is created, then the conversion does not automatically want to start**

**in manual mode i run with parameters:**

`sudo -u bigbluebutton docker-compose run --rm --user 111:119 app node index.js -i /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595 -o /var/bigbluebutton/published/presentation/5941b4e7060e134bb7389947897204258fdf5a11-1603880721595/video.mp4`

**Comment by MOPO3KO** [comment]
Thanks for developing the script!
I found my mistakes in the old version and corrected it, now the conversion works both in manual mode and automatically.

A big request, when creating new scripts, add containers for offline download.
A small number of system users, to whom I am concerned, have limited ability to turn on the Internet on the server (((

And if it's not difficult, add a chat for conversion :)

**Comment by tilmanmoser** [comment]
Hi there. Glad you got this up and running. For the offline part: How do you even install docker then? You could build a container locally and transfer to your server... I will not add features any time soon - year's end has other things for me to handle first.
