### ISSUE TITLE
cannot unmarshal string into Go value of type types.Seccomp

### ISSUE THREAD

**Issue by human-bieng** [tilmanmoser/bbb-video-download#44]
Hello there 
I have used the new docker script but it failed to convert & throws the following error 
Cannot start service app: Decoding seccomp profile failed: json: cannot unmarshal string into Go value of type types.Seccomp
Any help will b e appreciated

**Comment by christmart** [comment]
Hi,
i experience the same problem. I tried to run it on the normal bbb node running on Ubuntu 16.04.
The first problem was the to old docker-compose package. It does not support the compose-file format 3.3.
So I installed docker-compose from Ubuntu 18.04. Then I get the messages you quoted.
Even after installing docker-ce from docker.com instead of docker from Ubuntu, the problem persists.

**Comment by human-bieng** [comment]
> 
> 
> Hi,
> i experience the same problem. I tried to run it on the normal bbb node running on Ubuntu 16.04.
> The first problem was the to old docker-compose package. It does not support the compose-file format 3.3.
> So I installed docker-compose from Ubuntu 18.04. Then I get the messages you quoted.
> Even after installing docker-ce from docker.com instead of docker from Ubuntu, the problem persists.

Hello brother
I solved the issue by updating docker-compose from version 1.18.0 to version 1.27.4 & it working as expected

**Comment by human-bieng** [comment]
> 
> 
> Hello there
> I have used the new docker script but it failed to convert & throws the following error
> Cannot start service app: Decoding seccomp profile failed: json: cannot unmarshal string into Go value of type types.Seccomp
> Any help will b e appreciated

Issue fixed on Ubuntu 18 by updating docker-compose to latest version

**Comment by christmart** [comment]
The version of docker-compose in Ubuntu 18 (bionic) is 1.17.1-2.
So from which repository did you install version 1.27.4 ?
In the meantime I used as a workaround
"seccomp:unrestricted" since chrome.json essentially allow 302 system calls.

**Comment by human-bieng** [comment]
i get it using the following command
# Docker compose installation
sudo curl -L
https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname
-s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x
/usr/local/bin/docker-compose

# Check Docker compose is installed
docker-compose --version
