### ISSUE TITLE
Bigbluebutton playback video is 3 hours, but bbb-video-download result is 1.07!

### ISSUE THREAD

**Issue by ahmdqader** [tilmanmoser/bbb-video-download#49]
Bigbluebutton playback video is 3 hours, but bbb-video-download result is 1.07 hour!

**Comment by tilmanmoser** [comment]
Please provide some detail. Best: The presentation files. Minimum: shapes.svg and metadata.xml

**Comment by ahmdqader** [comment]
Should I upload the files or just screenshots for the files

**Comment by tilmanmoser** [comment]
please provide the files (not screenshots)
