### ISSUE TITLE
 Errors

### ISSUE THREAD

**Issue by ilokitv** [tilmanmoser/bbb-video-download#5]
[ffmetadata @ 0x562a31e37400] Chapter end time 42127 before start 86100
./tmp/2b47e8f52d4bb4fc25639b813efe89f98dd9cfb7-1599713865686/ffmetadata.txt: Cannot allocate memory

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Processor.createVideo (/opt/bbb-video-download/modules/processor.js:65:26)
    at async process (/opt/bbb-video-download/index.js:40:9) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 32 2e 32 2d 31 62 62 62 31 7e 75 62 75 6e 74 75 31 36 2e 30 34 20 43 6f 70 79 72 69 67 68 74 20 28 ... 5795 more bytes>
  ],
  pid: 106702,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 32 2e 32 2d 31 62 62 62 31 7e 75 62 75 6e 74 75 31 36 2e 30 34 20 43 6f 70 79 72 69 67 68 74 20 28 ... 5795 more bytes>
}

**Comment by tilmanmoser** [comment]
Thanks for reporting this issue. At first glance it seems, that this is related to the number of threads used by ffmpeg. I'll have some tests and will provide a way to limit threads.

**Comment by tilmanmoser** [comment]
Hi - checkout v1.0.6. The threads used by ffmpeg are now limited to default 1. Please check, if your video is rendered with that settings. If so, you can try out (if needed) what's a good number of threads on your specific machine.

**Comment by ilokitv** [comment]
> Привет - оформление заказа v1.0.6. Потоки, используемые ffmpeg, теперь ограничены значением по умолчанию 1. Пожалуйста, проверьте, отображается ли ваше видео с этими настройками. Если да, вы можете попробовать (при необходимости), какое количество потоков на вашем конкретном компьютере.
15. pumped flows, it is still an error

**Comment by tilmanmoser** [comment]
Can you provide me more logs? Or even better the presentation, you try to render?

**Comment by ilokitv** [comment]
[log.txt](https://github.com/tilmanmoser/bbb-video-download/files/5200254/log.txt)

**Comment by tilmanmoser** [comment]
Thanks. Can you also provide the created ffmetadata.txt? It's located in your installdir ./tmp/2b47e8f52d4bb4fc25639b813efe89f98dd9cfb7-1599713865686/ffmetadata.txt

**Comment by ilokitv** [comment]
[ffmetadata.txt](https://github.com/tilmanmoser/bbb-video-download/files/5200354/ffmetadata.txt)

**Comment by tilmanmoser** [comment]
Ok. There's a wrong start/end-time in ffmetadata.txt. I'll check what's wrong here.

**Comment by tilmanmoser** [comment]
Hi - just want to give a lifesign. I'll look into this at the weekend. Sorry for the long delay. I'm very busy atm with things that earn me my rent and bread :-)

**Comment by ilokitv** [comment]
no problems. Thanks for your work

**Comment by tilmanmoser** [comment]
I'll removed the chapters for the time beeing. It may come back, but since it's not vital, I stripped it from the feature list for the mvp.
