### ISSUE TITLE
After upgrade to docker 5:20.10.4~3-0~ubuntu-xenial on 16.04, processing hangs

### ISSUE THREAD

**Issue by ichdasich** [tilmanmoser/bbb-video-download#52]
After upgrading to docker `5:20.10.4~3-0~ubuntu-xenial` on 16.04, execution hangs when attaching the container in interactive mode. A downgrade to `5:20.10.3~3-0~ubuntu-xenial` fixed the issue.

I assume this is somewhat related to interactive attaching waiting for something, but would have to dig `5:20.10.4~3-0~ubuntu-xenial` release notes for a better clue.

**Comment by tilmanmoser** [comment]
Thanks for the info. Could you test, wether "downgrading" the used service-version in docker-compose.yml to "2.4" would work with the latest docker-version? Since I'm not using any 3.0-features, this would be worth a try.

**Comment by ichdasich** [comment]
Currently quiet loaded, if opportunity comes around i will do that. Can you maybe bump this ticket in a week or two?

**Comment by ichdasich** [comment]
Seems to have been a self-solving issue; bug in docker, see https://github.com/docker/for-linux/issues/1212

Will verify later today.
