### ISSUE TITLE
Changing output layout

### ISSUE THREAD

**Issue by hosseinshokrzadeh** [tilmanmoser/bbb-video-download#54]
Hey there, thank you for providing such a good utility

i was wondering how can i change the output layout?

**Comment by tilmanmoser** [comment]
Hi there,

assuming that "output layout" refers to the composition of deskshare/presentation with the webcams video, there's no configuration option available. If you'd like to tweak the code, have a look into this:

At [processor.js#L41](https://github.com/tilmanmoser/bbb-video-download/blob/e18080c6d595bf82e14804b42b8596316039374f/src/modules/processor.js#L41) the script detects, which composable parts are available (i.e. presentation only, presentation w/ audio, webcams only, presentation w/ webcams). In case there's a presentation & webcams available, they're combined at [processor.js#L69](https://github.com/tilmanmoser/bbb-video-download/blob/e18080c6d595bf82e14804b42b8596316039374f/src/modules/processor.js#L69). Here you could change the layout (i.e. position & width of the webcams video).
