### ISSUE TITLE
Decoding seccomp profile failed: json: cannot unmarshal string into Go value of type seccomp.Seccomp

### ISSUE THREAD

**Issue by jeanz6** [tilmanmoser/bbb-video-download#58]
Hey guys I very like your work. Thanks to all who contribute!
 I installed everything like the README said. 
But I cant use the docker-compose command without error. 
I tried it like this:
 `sudo -u bigbluebutton docker-compose run --rm --user 998:998 app node index.js -i /var/bigbluebutton/published/presentation/b74a1c0745a341faa3aa9a2076e56787d6cc3979-1616582219178 -o /var/bigbluebutton/published/presentation/b74a1c0745a341faa3aa9a2076e56787d6cc3979-1616582219178/video.mp4
`

and also like this:
 ` sudo -u bigbluebutton docker-compose run --rm --user=998:998 app node index.js -h
` to just get the help commands showing.

But everytime I run those commands i get this error:

`ERROR: Cannot start service app: Decoding seccomp profile failed: json: cannot unmarshal string into Go value of type seccomp.Seccomp`

if its helps here are the versions of docker and docker-compose: 
Docker version 20.10.5, build 55c4c88
docker-compose version 1.18.0, build 8dd22a9

I was looking for a small fast solution for converting the recordings to mp4 and this project seems to be perfect, can someone help me?

**Comment by ichdasich** [comment]
upgrade your version of docker-compose. Had the same issue when evaluating on 2.3

**Comment by jeanz6** [comment]
helped! thanks! :)
