### ISSUE TITLE
Process fails when presentation has a high number of SVG-Shapes (1000+)

### ISSUE THREAD

**Issue by wolbernd** [tilmanmoser/bbb-video-download#6]
When converting a presentation that has lots of SVG-Shapes (Whiteboard-Shapes) the conversion process fails with the message
```
Error: spawnSync /bin/sh E2BIG
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:616:24)
    at Object.execSync (child_process.js:661:15)
    at Processor.createVideo (/srv/recstore/videogenerator/modules/processor.js:65:26)
    at async process (/srv/recstore/videogenerator/index.js:55:9) {
  errno: 'E2BIG',
  code: 'E2BIG',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
```
My guess is that the ffmpeg command line gets too long.

I created an example presentation which you can download here: https://fz-juelich.sciebo.de/s/dWpQCnv2eB6kxp1
A logfile for the conversion process is also included in the zip file.

**Comment by tilmanmoser** [comment]
Thanks for providing such great detail. Will have a look into it!

**Comment by tilmanmoser** [comment]
Your "exzessive" use of whiteboard brought me back to the concept board. A solution I can think of, is to render each slide separately into a small video and to concatenate those before stacking it to the webcams video. Since I'm very busy with other things atm, this will take some days. Stay tuned :-)

**Comment by tilmanmoser** [comment]
Hi - just want to give a ping. I will look into this at the weekend.

**Comment by tilmanmoser** [comment]
Hi. I am able to render this usecase now iteratively. But it's painfully slow. So, I'm still testing alternatives.

**Comment by beillahi** [comment]
Hello. 
We are currently trying to process some seminar recordings and we are also getting the same issue. Is there some hope that it might be solved soon?  Thanks

**Comment by christmart** [comment]
Two ideas:

- the script could cd into the recording directory like presentation/3151100dfc2083fa9851fda5e8e8f9a0da3b8067-1602571117470/presentation/ and spare this path in every image path.

- the script could put all the complex_filter commands in a text file and call it with filter_complex_script..

**Comment by christmart** [comment]
#19 puts all filters in a file

**Comment by aaswaisi** [comment]
Is there a solution to this problem? @tilmanmoser

**Comment by christmart** [comment]
The version release a week ago is a lot better.

**Comment by tilmanmoser** [comment]
This particular issue is solved. There'll be a fix for desksharing today/tomorrow.
