### ISSUE TITLE
Tune ffmpeg

### ISSUE THREAD

**Issue by sparse91** [tilmanmoser/bbb-video-download#62]
Hello
Thank you for your work
ffmpeg jobs are slow. Can we tune them by increasing threads? Is that OK? What do you recommend?

**Comment by tilmanmoser** [comment]
Yes, you can (by changing the script). The script only uses one thread/core on purpose. The consideration behind is, that if the script is invoked by a post_publish hook it most probably is running on the same machine, that is hosting your meetings and should not use too much resources. Also, you might have multiple conversions triggered simultaneously. If you process the videos on a separate machine in a cued manner, it makes sense to use as many cores as are available. 

You can checkout the script and globally search and replace `-threads 1` with your desired settings...

**Comment by sparse91** [comment]
Thanks
