### ISSUE TITLE
bbb2.3 error

### ISSUE THREAD

**Issue by osintaras** [tilmanmoser/bbb-video-download#67]
Hello!
In manual mode create video 
sudo -u bigbluebutton docker-compose run --rm --user 998:998 app node index.js -i /var/bigbluebutton/published/presentation/fe2ef495a1152561572949784c16bf23abb28057-1623605762273 -o /var/bigbluebutton/published/presentation/fe2ef495a1152561572949784c16bf23abb28057-1623605762273.mp4

gets error:
ERROR: Cannot start service app: Decoding seccomp profile failed: json: cannot unmarshal string into Go value of type seccomp.Seccomp
What am I doing wrong?

**Comment by osintaras** [comment]
Dear @tilmanmoser, Do you have any idea about this error?

**Comment by osintaras** [comment]
After updating docker error fixed, but new one appeared:

Creating bbb-video-download_app_run ... done
WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
[Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/fe2ef495a1152561572949784c16bf23abb28057-1623605762273', output='/var/bigbluebutton/published/presentation/fe2ef495a1152561572949784c16bf23abb28057-1623605762273.mp4'),
  format: 'mp4',
  docker: true
}
[Error] Failed rendering downloable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/fe2ef495a1152561572949784c16bf23abb28057-1623605762273', output='/var/bigbluebutton/published/presentation/fe2ef495a1152561572949784c16bf23abb28057-1623605762273.mp4'),
  format: 'mp4',
  docker: true
} Error: EACCES: permission denied, mkdtemp './tmp/dataXXXXXX'
    at Object.mkdtempSync (fs.js:1872:3)
    at module.exports.createVideo (/home/bigbluebutton/modules/processor.js:13:25)
    at run (/home/bigbluebutton/index.js:10:15)
    at Object.<anonymous> (/home/bigbluebutton/index.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'mkdtemp',
  code: 'EACCES',
  path: './tmp/dataXXXXXX'
}

**Comment by osintaras** [comment]
set 777 attributes to tmp folder
and change --user 998:998 to --user 997:996
problem solved

**Comment by tilmanmoser** [comment]
Hi. Sorry for late reply. Check readme - one can‘t assume uid/gid is always the same on each system. That‘s why uid/gid is read from /etc/passwd
