### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by faz17** [tilmanmoser/bbb-video-download#7]
Hello,
when i try to install i receive the error "found 1 high severity vulnerability" . Exploring the details i noted the error is caused by the package puppeteer that is required a version >=1.13.0 but during the installation problem he try to install 1.1.0
Any help?

Thanks

**Comment by mtsonline** [comment]
Hi Tilman,
I also get this and several other errors/warnings during install on a clean 2.2.25 bigBlueButton server:
...
```
npm WARN notsup Unsupported engine for w3c-xmlserializer@2.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: w3c-xmlserializer@2.0.0
npm WARN notsup Unsupported engine for webidl-conversions@6.1.0: wanted: {"node":">=10.4"} (current: {"node":"8.17.0","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: webidl-conversions@6.1.0
npm WARN notsup Unsupported engine for whatwg-url@8.2.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: whatwg-url@8.2.2
npm WARN notsup Unsupported engine for jest-each@26.4.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.17.0","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: jest-each@26.4.2
npm WARN bbb-video-download@1.0.6 No repository field.

added 583 packages from 433 contributors and audited 584 packages in 27.969s

21 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by wolbernd** [comment]
@mtsonline It looks like your calling npm from the nodejs installed by BBB. Try entering the bbb-vide-download folder and run ./node12/bin/npm install

**Comment by mtsonline** [comment]
thanks. I just followed the steps from the README. :-)
Now I get the following output, does that mean it is okay?

```
root@bbb30:/opt/bbb-video-download# ./node12/bin/npm install
npm WARN bbb-video-download@1.0.6 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 584 packages in 5.238s

21 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.14.6 → 6.14.8       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.8   │
   │               Run npm install -g npm to update!                │
   │                                                                │
```

**Comment by wolbernd** [comment]
@mtsonline It should be fine I think. Just try to run a manual conversion on a presentation and if this runs without a problem everything is fine.

**Comment by tilmanmoser** [comment]
Warnings are not errors. I'm using some third party npm packages, which I can't fix and won't reimplement them.

**Comment by mtsonline** [comment]
@tilmanmoser yes, but
found 1 high severity vulnerability
does not sound nice ;-) 
Maybe you could add some "installed correctly" at the end or something similar so one would know that it worked.

And please change the README to reflect the working install command from above, as the ./install does not work.

cheers

**Comment by tilmanmoser** [comment]
Hi there. I'll provide a dockerized installation in the next round... stay stuned.

**Comment by tilmanmoser** [comment]
v1.2.1 provides dockerized installation. So all the mess with different node version and chromium browsers are taken away from the user :-)

**Comment by mtsonline** [comment]
thanks a lot, that's great news!

cheers


Am 05.11.2020 um 12:01 schrieb Tilman Moser:
