### ISSUE TITLE
Poll results in downloaded mp4

### ISSUE THREAD

**Issue by drlight17** [tilmanmoser/bbb-video-download#71]
Hi. I'm testing BBB 2.4-RC1 now and I found that poll results is not shown in produced mp4 video of presentation. See attached screenshot:
![image](https://user-images.githubusercontent.com/37434652/136688549-809600ef-9403-4cc5-994d-353dc9e71310.png)
And this is presentation in player:
![image](https://user-images.githubusercontent.com/37434652/136688583-6b5acc41-8e65-4949-8921-916818181b86.png)

Did I miss something while install dockerized script?

**Comment by tilmanmoser** [comment]
Polls are not supported. In no version. Feel free to add this feature :-)
