### ISSUE TITLE
Final recording does not contain screenshare

### ISSUE THREAD

**Issue by matiasilva** [tilmanmoser/bbb-video-download#8]
Hello!

Just tested this out earlier today and noticed that my final recording rendered correctly but did not contain the screenshare. I noticed that in the ffmpeg call it wasn't added as an input source. Do you have any idea why? I believe I followed the instructions and did as told by the README.

**Comment by tilmanmoser** [comment]
Thanks for reporting this. Can you share an example? Screensharing is working in my (real world) examples.

**Comment by tilmanmoser** [comment]
Fixed in v1.1.1

**Comment by christmart** [comment]
Please push your git tags, so that one can see which commits are in v1.0.x or v1.1.x .

**Comment by tilmanmoser** [comment]
I should even start to tag properly :-) Version is related to the version in package.json so far... I'll tag further commits.
