### ISSUE TITLE
record without audio

### ISSUE THREAD

**Issue by piscu7** [tilmanmoser/bbb-video-download#9]
video.mp4 completed successfully but video.mp4 without audio. can you help me please?

**Comment by piscu7** [comment]
help please?

**Comment by miriyusifli** [comment]
Check logs under **/var/log/bigbluebutton/post_publish.log** to find the problem. It should be worked properly.

**Comment by piscu7** [comment]
@miriyusifli  thanks for reply.  i checked post_publish.log but no error

I, [2020-09-25T19:15:49.981695 #27122]  INFO -- : Task: Getting meeting metadata
I, [2020-09-25T19:15:49.999250 #27122]  INFO -- : Recording Ready Notify for [d43bc745a8bd3eca73b38cb75d7ba31236cb8972-1601036361939] starts
I, [2020-09-25T19:15:49.999323 #27122]  INFO -- : Recording Ready notify ends

**Comment by tilmanmoser** [comment]
Is this still a issue with the latest versions of the script?

**Comment by tilmanmoser** [comment]
Also: In the logs the script was not even called. Closing due to ne user input.
